---
title: "STAT 545A Homework 5"
author: "Junbin ZHANG"
date: "Oct 09, 2018"
output:
  html_document:
    keep_md: true
    toc: true
    theme: readable
---

# Bring rectangular data in

```r
## load gapminder
suppressPackageStartupMessages(library(gapminder))
## load tidyverse
suppressPackageStartupMessages(library(tidyverse))
## load forcats
suppressPackageStartupMessages(library(forcats))
## load plotly
suppressPackageStartupMessages(library(plotly))
```

# Part 1: Factor management

## Drop Oceania

Before dropping Oceania, let's check the number of rows in `gapminder`, and the levels of `continent`.


```r
gapminder %>% 
  # get the number of rows and levels of continent
  summarize(
    nrow = nrow(gapminder),
    nlevels = nlevels(gapminder$continent)
  ) %>% 
  # show the table
  knitr::kable(col.names = c("Number of rows", "Levels of `continent`"))
```



 Number of rows   Levels of `continent`
---------------  ----------------------
           1704                       5


Let's first try to drop Oceania, and show the number of rows, and the levels of `continent`.


```r
# drop Oceania
drop <- gapminder %>% 
  filter(continent != "Oceania")

drop %>% 
  # get the number of rows and levels of continent
  summarize(
    nrow = nrow(drop),
    nlevels = nlevels(drop$continent)
  ) %>% 
  # show the table
  knitr::kable(col.names = c("Number of rows after dropping", "Levels of `continent` after dropping"))
```



 Number of rows after dropping   Levels of `continent` after dropping
------------------------------  -------------------------------------
                          1680                                      5

Here we can see, even we remove all rows associated with the `continent` of Oceania (so the number of rows decrease), the levels of `continent` is unchanged. However, it is a wrong value. To fix it, we need to `droplevels()` to solve the issue.


```r
# drop levels
drop_levels <- drop %>% 
  droplevels()

drop_levels %>% 
  # get the number of rows and levels of continent
  summarize(
    nrow = nrow(drop_levels),
    nlevels = nlevels(drop_levels$continent)
  ) %>% 
  # show the table
  knitr::kable(col.names = c("Number of rows after dropping levels", "Levels of `continent` after dropping levels"))
```



 Number of rows after dropping levels   Levels of `continent` after dropping levels
-------------------------------------  --------------------------------------------
                                 1680                                             4

To summarize, we address the number of rows and the levels of `continent` before and after removing Oceania.


```r
# build a tibble with statistics
summary <- cbind(
  before = c(
    nrow(gapminder),
    nlevels(gapminder$continent)
  ),
  after = c(
    nrow(drop_levels),
    nlevels(drop_levels$continent)
  )
)

# assign row names
rownames(summary) <- c("Number of rows", "Levels")

# display the table
summary %>% 
  knitr::kable()
```

                  before   after
---------------  -------  ------
Number of rows      1704    1680
Levels                 5       4

## Reorder the levels of `country` and `continent`

Let's show a preview of our dropped version of `gapminder` before reordering.


```r
# show previews
head(drop_levels) %>% 
  knitr::kable()
```



country       continent    year   lifeExp        pop   gdpPercap
------------  ----------  -----  --------  ---------  ----------
Afghanistan   Asia         1952    28.801    8425333    779.4453
Afghanistan   Asia         1957    30.332    9240934    820.8530
Afghanistan   Asia         1962    31.997   10267083    853.1007
Afghanistan   Asia         1967    34.020   11537966    836.1971
Afghanistan   Asia         1972    36.088   13079460    739.9811
Afghanistan   Asia         1977    38.438   14880372    786.1134

```r
tail(drop_levels) %>% 
  knitr::kable()
```



country    continent    year   lifeExp        pop   gdpPercap
---------  ----------  -----  --------  ---------  ----------
Zimbabwe   Africa       1982    60.363    7636524    788.8550
Zimbabwe   Africa       1987    62.351    9216418    706.1573
Zimbabwe   Africa       1992    60.377   10704340    693.4208
Zimbabwe   Africa       1997    46.809   11404948    792.4500
Zimbabwe   Africa       2002    39.989   11926563    672.0386
Zimbabwe   Africa       2007    43.487   12311143    469.7093

From a bigger picture, this data frame is ordered by the alphabetical order of `country`. Let's try to reorder the levels of `country` by the maximum population over the years using `fct_reorder()`. Note that it is reordered in ascending order, so the first level is the one with least maximum population over the year.


```r
fct_reorder(
  # reorder country
  drop_levels$country,
  # by pop
  drop_levels$pop,
  # using maximum
  max) %>%
  # show preview of resultant levels
  levels() %>% 
  head() %>% 
  knitr::kable(col.names = c("`country` after reordering"))
```



|`country` after reordering |
|:--------------------------|
|Sao Tome and Principe      |
|Iceland                    |
|Djibouti                   |
|Equatorial Guinea          |
|Bahrain                    |
|Comoros                    |

In order to check our results, we manually calculate the maximum population and order it.


```r
drop_levels %>% 
  # group by country
  group_by(country) %>% 
  # calcuate maximum population for each country
  summarize(
    max_pop = max(pop)
  ) %>% 
  # arrange by max_pop
  arrange(max_pop) %>%
  # show preview
  head() %>% 
  knitr::kable(col.names = c("country", "Maximum population over the years"))
```



country                  Maximum population over the years
----------------------  ----------------------------------
Sao Tome and Principe                               199579
Iceland                                             301931
Djibouti                                            496374
Equatorial Guinea                                   551201
Bahrain                                             708573
Comoros                                             710960

So our operation using `fct_reorder` is correct.

We can do the same thing on `continent`. For example, we reorder its levels by the average life expectancy.


```r
fct_reorder(
  # reorder continent
  drop_levels$continent,
  # by lifeExp
  drop_levels$lifeExp,
  # using mean
  mean) %>%
  # show preview of resultant levels
  levels() %>% 
  head() %>% 
  knitr::kable(col.names = c("`continent` after reordering"))
```



|`continent` after reordering |
|:----------------------------|
|Africa                       |
|Asia                         |
|Americas                     |
|Europe                       |

We also double-check the results.


```r
drop_levels %>% 
  # group by continent
  group_by(continent) %>% 
  # calcuate mean lifeExp for each continent
  summarize(
    mean_lifeExp = mean(lifeExp)
  ) %>% 
  # arrange by mean_lifeExp
  arrange(mean_lifeExp) %>%
  # show preview
  head() %>% 
  knitr::kable(col.names = c("continent", "Average life expectancy over the years"))
```



continent    Average life expectancy over the years
----------  ---------------------------------------
Africa                                     48.86533
Asia                                       60.06490
Americas                                   64.65874
Europe                                     71.90369

## Characterize the (derived) data

In the previous section, we try to create two examples using `fct_reorder()` and `arrange()`, with identical results. Now, we try to reuse the first example and see if these two functions affect figures generated.

Let's try the first example, using `fct_reorder()` only.


```r
drop_levels %>%
  # try to only show a continent
  filter(continent == "Americas") %>% 
  # group by country
  group_by(country) %>% 
  # calcuate maximum population for each country
  mutate(
    max_pop = max(pop)
  ) %>%
  # show preview of resultant levels
  ggplot(aes(x = max_pop, y = fct_reorder(country, pop, max), color = country)) +
  # make it a scatterplot
  geom_point() + 
  # scale x axis by log10
  scale_x_log10() +
  # change axis labels
  xlab("Maximum population") +
  ylab("country") +
  # add title
  labs(title = "Maximum population of countries in Americas") +
  # change theme
  theme_bw()
```

![](hw05_files/figure-html/unnamed-chunk-11-1.png)<!-- -->

Let's do it with `arrange()` only.


```r
drop_levels %>% 
  # try to only show a continent
  filter(continent == "Americas") %>% 
  # group by country
  group_by(country) %>% 
  # calcuate maximum population for each country
  summarize(
    max_pop = max(pop)
  ) %>% 
  # arrange by max_pop
  arrange(max_pop) %>%
  # show preview of resultant levels
  ggplot(aes(x = max_pop, y = country, color = country)) +
  # make it a scatterplot
  geom_point() + 
  # scale x axis by log10
  scale_x_log10() +
  # change axis labels
  xlab("Maximum population") +
  ylab("country") +
  # add title
  labs(title = "Maximum population of countries in Americas") +
  # change theme
  theme_bw()
```

![](hw05_files/figure-html/unnamed-chunk-12-1.png)<!-- -->

Now we use `fct_reorder()` with `arrange()`.


```r
drop_levels %>% 
  # try to only show a continent
  filter(continent == "Americas") %>% 
  # group by country
  group_by(country) %>% 
  # calcuate maximum population for each country
  mutate(
    max_pop = max(pop)
  ) %>% 
  # arrange by max_pop
  arrange(max_pop) %>%
  # show preview of resultant levels
  ggplot(aes(x = max_pop, y = fct_reorder(country, pop, max), color = country)) +
  # make it a scatterplot
  geom_point() + 
  # scale x axis by log10
  scale_x_log10() +
  # change axis labels
  xlab("Maximum population") +
  ylab("country") +
  # add title
  labs(title = "Maximum population of countries in Americas") +
  # change theme
  theme_bw()
```

![](hw05_files/figure-html/unnamed-chunk-13-1.png)<!-- -->

**Finding(s):** using `fct_reorder()` (no matter with `arrange()` or not) will change the order of levels shown in figures, while using `arrange()` along will not affect the order of levels. 

# Part 2: File I/O

In order to test if mutated data can survire the round trip of writing and then reading back from a file, we first use the first example in Part 1 to mutate `gapminder`.


```r
data <- gapminder %>% 
  # mutate country by maximum population
  mutate(
    country = fct_reorder(country, pop, max)
  ) %>% 
  # group by country
  group_by(country) %>% 
  # calculate maximum population
  summarize(
    max_pop = max(pop)
  )
  
# show summary of the data
data %>% 
  glimpse()
```

```
## Observations: 142
## Variables: 2
## $ country <fct> Sao Tome and Principe, Iceland, Djibouti, Equatorial G...
## $ max_pop <dbl> 199579, 301931, 496374, 551201, 708573, 710960, 720230...
```

```r
# show previews
head(data) %>% 
  knitr::kable()
```



country                  max_pop
----------------------  --------
Sao Tome and Principe     199579
Iceland                   301931
Djibouti                  496374
Equatorial Guinea         551201
Bahrain                   708573
Comoros                   710960

```r
tail(data) %>% 
  knitr::kable()
```



country             max_pop
--------------  -----------
Pakistan          169270617
Brazil            190010647
Indonesia         223547000
United States     301139947
India            1110396331
China            1318683096

## `write_csv()/read_csv()`


```r
# write to csv
write_csv(data, "data_csv.csv")
# read from csv
data_csv <- read_csv("data_csv.csv")
```

```
## Parsed with column specification:
## cols(
##   country = col_character(),
##   max_pop = col_double()
## )
```

```r
# show summary of the data
data_csv %>% 
  glimpse()
```

```
## Observations: 142
## Variables: 2
## $ country <chr> "Sao Tome and Principe", "Iceland", "Djibouti", "Equat...
## $ max_pop <dbl> 199579, 301931, 496374, 551201, 708573, 710960, 720230...
```

```r
# show previews
head(data_csv) %>% 
  knitr::kable()
```



country                  max_pop
----------------------  --------
Sao Tome and Principe     199579
Iceland                   301931
Djibouti                  496374
Equatorial Guinea         551201
Bahrain                   708573
Comoros                   710960

```r
tail(data_csv) %>% 
  knitr::kable()
```



country             max_pop
--------------  -----------
Pakistan          169270617
Brazil            190010647
Indonesia         223547000
United States     301139947
India            1110396331
China            1318683096

**Finding(s):** using CSV format, it requires R to parse each column with default formats. Therefore, the class of `country` changes from `<fct>` to `<chr>`. However, the data keeps unchanged.

## `saveRDS()/readRDS()`


```r
# save to rds
saveRDS(data, "data_rds.rds")
# read from rds
data_rds <- readRDS("data_rds.rds")

# show summary of the data
data_rds %>% 
  glimpse()
```

```
## Observations: 142
## Variables: 2
## $ country <fct> Sao Tome and Principe, Iceland, Djibouti, Equatorial G...
## $ max_pop <dbl> 199579, 301931, 496374, 551201, 708573, 710960, 720230...
```

```r
# show previews
head(data_rds) %>% 
  knitr::kable()
```



country                  max_pop
----------------------  --------
Sao Tome and Principe     199579
Iceland                   301931
Djibouti                  496374
Equatorial Guinea         551201
Bahrain                   708573
Comoros                   710960

```r
tail(data_rds) %>% 
  knitr::kable()
```



country             max_pop
--------------  -----------
Pakistan          169270617
Brazil            190010647
Indonesia         223547000
United States     301139947
India            1110396331
China            1318683096

**Finding(s):** `saveRDS()` and `readRDS()` can keep both data and classes of each column.

## `dput()/dget()`


```r
# put to file
dput(data, "data.txt")
# get from file
data_get <- dget("data.txt")

# show summary of the data
data_get %>% 
  glimpse()
```

```
## Observations: 142
## Variables: 2
## $ country <fct> Sao Tome and Principe, Iceland, Djibouti, Equatorial G...
## $ max_pop <dbl> 199579, 301931, 496374, 551201, 708573, 710960, 720230...
```

```r
# show previews
head(data_get) %>% 
  knitr::kable()
```



country                  max_pop
----------------------  --------
Sao Tome and Principe     199579
Iceland                   301931
Djibouti                  496374
Equatorial Guinea         551201
Bahrain                   708573
Comoros                   710960

```r
tail(data_get) %>% 
  knitr::kable()
```



country             max_pop
--------------  -----------
Pakistan          169270617
Brazil            190010647
Indonesia         223547000
United States     301139947
India            1110396331
China            1318683096

**Finding(s):** `dput()` and `dget()` can also keep both data and classes of each column.

# Part 3: Visualization design

Here I want to remake an figure I used in the first assignment. It tries to show the trends of population over the years for each continent.


```r
# this is the figure copy from assignment 1, so no fancy operation is done
p_ori <- gapminder %>% 
  # year as x axis and pop as y axis
  ggplot(aes(x = year, y = pop)) +
  # scale y axis by log10
  scale_y_log10() +
  # make it a scatterplot, and add transparancy
  geom_point(alpha = 0.1) +
  # show colors
  aes(color = continent) + 
  # facetting by continent
  facet_wrap(~ continent)
p_ori
```

![](hw05_files/figure-html/unnamed-chunk-18-1.png)<!-- -->

We cannot get too much information for this figure. Therefore, we try to tidy up data, and make better presentation (e,g, color, size) to make it more reasonable.


```r
# tidy up data
tidy_up <- gapminder %>% 
  # group by year and continent
  group_by(year, continent) %>%
  # calcuate summaries of pop
  summarize(
    min_pop = min(pop),
    mean_pop = mean(pop),
    max_pop = max(pop)
  ) %>% 
  # gather pop into two columns
  gather(
    key = "pop_attribute",
    value = "pop_val",
    min_pop, mean_pop, max_pop
  )

# make new plot
p_new <- tidy_up %>% 
  # year as x axis and pop as y axis, group by pop_attribute
  ggplot(aes(x = year, y = pop_val, color = pop_attribute, group = pop_attribute)) +
  # scale y axis by log10
  scale_y_log10() +
  # make it a line plot (with points)
  geom_point() +
  geom_line() +
  # facetting by continent
  facet_wrap(~ continent) +
  # modify labels
  ylab("Population distribution") +
  scale_color_discrete("Population distribution") +
  # add title
  labs(
    title = "Population distribution of each continent over the years"
  ) +
  # make a better x axis
  scale_x_continuous(breaks = scales::pretty_breaks(n = 4)) +
  # add theme
  theme_bw() +
  theme(
    strip.background = element_rect(fill = "grey"),
    panel.background = element_rect(fill = "white")
  )
p_new
```

![](hw05_files/figure-html/unnamed-chunk-19-1.png)<!-- -->

**Difference(s):** the color in the new figure is not for each continent, but for different distributions of each continent, which makes more sense. In addition, we try to tidy up data into different distribution attributes, so the trends over the years are clearer.

`plotly` is an R package for creating interactive web-based graphs. In the following simple example, the differences of using `plotly` are:

- There is a floating toolbar for users to interact with the figure, e.g saving figure, zooming.
- When users hover on each data point, the details of that data point are shown in a floating window.


```r
# convert a ggplot into plotly
ggplotly(p_new)
```

<!--html_preserve--><div id="htmlwidget-d1ce2cf55ba832358aeb" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-d1ce2cf55ba832358aeb">{"x":{"data":[{"x":[1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007],"y":[7.52007847401955,7.57023158392065,7.62191697384512,7.67474866869504,7.73029834901568,7.79385442793126,7.863557054218,7.91143206006005,7.97018058493844,8.0261565723839,8.07882379767959,8.13043401139359],"text":["year: 1952<br />pop_val:   33119096<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1957<br />pop_val:   37173340<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1962<br />pop_val:   41871351<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1967<br />pop_val:   47287752<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1972<br />pop_val:   53740085<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1977<br />pop_val:   62209173<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1982<br />pop_val:   73039376<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1987<br />pop_val:   81551520<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1992<br />pop_val:   93364244<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1997<br />pop_val:  106207839<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 2002<br />pop_val:  119901274<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 2007<br />pop_val:  135031164<br />pop_attribute: max_pop<br />pop_attribute: max_pop"],"type":"scatter","mode":"markers+lines","marker":{"autocolorscale":false,"color":"rgba(248,118,109,1)","opacity":1,"size":5.66929133858268,"symbol":"circle","line":{"width":1.88976377952756,"color":"rgba(248,118,109,1)"}},"hoveron":"points","name":"max_pop","legendgroup":"max_pop","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","line":{"width":1.88976377952756,"color":"rgba(248,118,109,1)","dash":"solid"},"frame":null},{"x":[1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007],"y":[8.19742667708184,8.2354880455417,8.27076731608707,8.29822409446976,8.32200416228664,8.34289422646615,8.36583946204006,8.38525500180701,8.40975428054592,8.43602225019194,8.45890291585187,8.47876836963079],"text":["year: 1952<br />pop_val:  157553000<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1957<br />pop_val:  171984000<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1962<br />pop_val:  186538000<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1967<br />pop_val:  198712000<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1972<br />pop_val:  209896000<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1977<br />pop_val:  220239000<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1982<br />pop_val:  232187835<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1987<br />pop_val:  242803533<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1992<br />pop_val:  256894189<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1997<br />pop_val:  272911760<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 2002<br />pop_val:  287675526<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 2007<br />pop_val:  301139947<br />pop_attribute: max_pop<br />pop_attribute: max_pop"],"type":"scatter","mode":"markers+lines","marker":{"autocolorscale":false,"color":"rgba(248,118,109,1)","opacity":1,"size":5.66929133858268,"symbol":"circle","line":{"width":1.88976377952756,"color":"rgba(248,118,109,1)"}},"hoveron":"points","name":"max_pop","legendgroup":"max_pop","showlegend":false,"xaxis":"x2","yaxis":"y","hoverinfo":"text","line":{"width":1.88976377952756,"color":"rgba(248,118,109,1)","dash":"solid"},"frame":null},{"x":[1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007],"y":[8.74528058512162,8.80441750992851,8.82332422168878,8.87768802344179,8.93552238021885,8.97472119043868,9.00012201960646,9.03504330439931,9.06631474166915,9.08993159200292,9.10734566547209,9.12014043906824],"text":["year: 1952<br />pop_val:  556263527<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1957<br />pop_val:  637408000<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1962<br />pop_val:  665770000<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1967<br />pop_val:  754550000<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1972<br />pop_val:  862030000<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1977<br />pop_val:  943455000<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1982<br />pop_val: 1000281000<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1987<br />pop_val: 1084035000<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1992<br />pop_val: 1164970000<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1997<br />pop_val: 1230075000<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 2002<br />pop_val: 1280400000<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 2007<br />pop_val: 1318683096<br />pop_attribute: max_pop<br />pop_attribute: max_pop"],"type":"scatter","mode":"markers+lines","marker":{"autocolorscale":false,"color":"rgba(248,118,109,1)","opacity":1,"size":5.66929133858268,"symbol":"circle","line":{"width":1.88976377952756,"color":"rgba(248,118,109,1)"}},"hoveron":"points","name":"max_pop","legendgroup":"max_pop","showlegend":false,"xaxis":"x3","yaxis":"y","hoverinfo":"text","line":{"width":1.88976377952756,"color":"rgba(248,118,109,1)","dash":"solid"},"frame":null},{"x":[1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007],"y":[7.8397667603597,7.85137497476913,7.86769793277751,7.88291399316423,7.89606901976115,7.89298884584857,7.8939573224812,7.89052328115443,7.90632299346847,7.9138724940683,7.91566714218713,7.91593246114723],"text":["year: 1952<br />pop_val:   69145952<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1957<br />pop_val:   71019069<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1962<br />pop_val:   73739117<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1967<br />pop_val:   76368453<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1972<br />pop_val:   78717088<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1977<br />pop_val:   78160773<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1982<br />pop_val:   78335266<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1987<br />pop_val:   77718298<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1992<br />pop_val:   80597764<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1997<br />pop_val:   82011073<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 2002<br />pop_val:   82350671<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 2007<br />pop_val:   82400996<br />pop_attribute: max_pop<br />pop_attribute: max_pop"],"type":"scatter","mode":"markers+lines","marker":{"autocolorscale":false,"color":"rgba(248,118,109,1)","opacity":1,"size":5.66929133858268,"symbol":"circle","line":{"width":1.88976377952756,"color":"rgba(248,118,109,1)"}},"hoveron":"points","name":"max_pop","legendgroup":"max_pop","showlegend":false,"xaxis":"x","yaxis":"y2","hoverinfo":"text","line":{"width":1.88976377952756,"color":"rgba(248,118,109,1)","dash":"solid"},"frame":null},{"x":[1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007],"y":[6.93908034356135,6.98733411713333,7.03322135927386,7.07453354531942,7.11981654593722,7.14842063247324,7.18139191546812,7.21104705754345,7.24259054452494,7.26870063806896,7.29107549160307,7.31035712964887],"text":["year: 1952<br />pop_val:    8691212<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1957<br />pop_val:    9712569<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1962<br />pop_val:   10794968<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1967<br />pop_val:   11872264<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1972<br />pop_val:   13177000<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1977<br />pop_val:   14074100<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1982<br />pop_val:   15184200<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1987<br />pop_val:   16257249<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1992<br />pop_val:   17481977<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 1997<br />pop_val:   18565243<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 2002<br />pop_val:   19546792<br />pop_attribute: max_pop<br />pop_attribute: max_pop","year: 2007<br />pop_val:   20434176<br />pop_attribute: max_pop<br />pop_attribute: max_pop"],"type":"scatter","mode":"markers+lines","marker":{"autocolorscale":false,"color":"rgba(248,118,109,1)","opacity":1,"size":5.66929133858268,"symbol":"circle","line":{"width":1.88976377952756,"color":"rgba(248,118,109,1)"}},"hoveron":"points","name":"max_pop","legendgroup":"max_pop","showlegend":false,"xaxis":"x2","yaxis":"y2","hoverinfo":"text","line":{"width":1.88976377952756,"color":"rgba(248,118,109,1)","dash":"solid"},"frame":null},{"x":[1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007],"y":[6.65991711566195,6.70697652624691,6.75604605615027,6.809416595297,6.86364256094897,6.92054575183267,6.98240048166202,7.04353918713089,7.10293578900756,7.1554720888603,7.20501891610603,7.25226459554954],"text":["year: 1952<br />pop_val:    4570010<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1957<br />pop_val:    5093033<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1962<br />pop_val:    5702247<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1967<br />pop_val:    6447875<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1972<br />pop_val:    7305376<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1977<br />pop_val:    8328097<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1982<br />pop_val:    9602857<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1987<br />pop_val:   11054502<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1992<br />pop_val:   12674645<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1997<br />pop_val:   14304480<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 2002<br />pop_val:   16033152<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 2007<br />pop_val:   17875763<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop"],"type":"scatter","mode":"markers+lines","marker":{"autocolorscale":false,"color":"rgba(0,186,56,1)","opacity":1,"size":5.66929133858268,"symbol":"circle","line":{"width":1.88976377952756,"color":"rgba(0,186,56,1)"}},"hoveron":"points","name":"mean_pop","legendgroup":"mean_pop","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","line":{"width":1.88976377952756,"color":"rgba(0,186,56,1)","dash":"solid"},"frame":null},{"x":[1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007],"y":[7.14007094678817,7.18971923743567,7.23881886506784,7.28397623355181,7.32583097473806,7.3640386940745,7.40160104203235,7.43632422606924,7.47086548490966,7.50346404159492,7.53136279774411,7.55575744937218],"text":["year: 1952<br />pop_val:   13806098<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1957<br />pop_val:   15478157<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1962<br />pop_val:   17330810<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1967<br />pop_val:   19229865<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1972<br />pop_val:   21175368<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1977<br />pop_val:   23122708<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1982<br />pop_val:   25211637<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1987<br />pop_val:   27310159<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1992<br />pop_val:   29570964<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1997<br />pop_val:   31876016<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 2002<br />pop_val:   33990910<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 2007<br />pop_val:   35954847<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop"],"type":"scatter","mode":"markers+lines","marker":{"autocolorscale":false,"color":"rgba(0,186,56,1)","opacity":1,"size":5.66929133858268,"symbol":"circle","line":{"width":1.88976377952756,"color":"rgba(0,186,56,1)"}},"hoveron":"points","name":"mean_pop","legendgroup":"mean_pop","showlegend":false,"xaxis":"x2","yaxis":"y","hoverinfo":"text","line":{"width":1.88976377952756,"color":"rgba(0,186,56,1)","dash":"solid"},"frame":null},{"x":[1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007],"y":[7.62617150478758,7.67538407119832,7.71100336195753,7.76153213920628,7.81412086724681,7.85888585587051,7.8981491272248,7.9395526458727,7.97748695644716,8.01082470758284,8.03800591949283,8.06263369164754],"text":["year: 1952<br />pop_val:   42283556<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1957<br />pop_val:   47356988<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1962<br />pop_val:   51404763<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1967<br />pop_val:   57747361<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1972<br />pop_val:   65180977<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1977<br />pop_val:   72257987<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1982<br />pop_val:   79095018<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1987<br />pop_val:   87006690<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1992<br />pop_val:   94948248<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1997<br />pop_val:  102523803<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 2002<br />pop_val:  109145521<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 2007<br />pop_val:  115513752<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop"],"type":"scatter","mode":"markers+lines","marker":{"autocolorscale":false,"color":"rgba(0,186,56,1)","opacity":1,"size":5.66929133858268,"symbol":"circle","line":{"width":1.88976377952756,"color":"rgba(0,186,56,1)"}},"hoveron":"points","name":"mean_pop","legendgroup":"mean_pop","showlegend":false,"xaxis":"x3","yaxis":"y","hoverinfo":"text","line":{"width":1.88976377952756,"color":"rgba(0,186,56,1)","dash":"solid"},"frame":null},{"x":[1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007],"y":[7.14418056572978,7.16424412081358,7.18597175597088,7.20518537262583,7.22240000484959,7.23650747703549,7.2481915046103,7.25775387804275,7.26962406969333,7.2779483800305,7.28497476060015,7.29084937666369],"text":["year: 1952<br />pop_val:   13937362<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1957<br />pop_val:   14596345<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1962<br />pop_val:   15345172<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1967<br />pop_val:   16039299<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1972<br />pop_val:   16687835<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1977<br />pop_val:   17238818<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1982<br />pop_val:   17708897<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1987<br />pop_val:   18103139<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1992<br />pop_val:   18604760<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1997<br />pop_val:   18964805<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 2002<br />pop_val:   19274129<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 2007<br />pop_val:   19536618<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop"],"type":"scatter","mode":"markers+lines","marker":{"autocolorscale":false,"color":"rgba(0,186,56,1)","opacity":1,"size":5.66929133858268,"symbol":"circle","line":{"width":1.88976377952756,"color":"rgba(0,186,56,1)"}},"hoveron":"points","name":"mean_pop","legendgroup":"mean_pop","showlegend":false,"xaxis":"x","yaxis":"y2","hoverinfo":"text","line":{"width":1.88976377952756,"color":"rgba(0,186,56,1)","dash":"solid"},"frame":null},{"x":[1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007],"y":[6.72778541803151,6.77604619837337,6.82228311292617,6.86333517487158,6.90596039556041,6.93548207399885,6.96366625508224,6.99065879595651,7.01952443930953,7.04613271085863,7.06920227535925,7.08902056321324],"text":["year: 1952<br />pop_val:    5343003<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1957<br />pop_val:    5970988<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1962<br />pop_val:    6641759<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1967<br />pop_val:    7300207<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1972<br />pop_val:    8053050<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1977<br />pop_val:    8619500<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1982<br />pop_val:    9197425<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1987<br />pop_val:    9787208<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1992<br />pop_val:   10459826<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 1997<br />pop_val:   11120715<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 2002<br />pop_val:   11727415<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop","year: 2007<br />pop_val:   12274974<br />pop_attribute: mean_pop<br />pop_attribute: mean_pop"],"type":"scatter","mode":"markers+lines","marker":{"autocolorscale":false,"color":"rgba(0,186,56,1)","opacity":1,"size":5.66929133858268,"symbol":"circle","line":{"width":1.88976377952756,"color":"rgba(0,186,56,1)"}},"hoveron":"points","name":"mean_pop","legendgroup":"mean_pop","showlegend":false,"xaxis":"x2","yaxis":"y2","hoverinfo":"text","line":{"width":1.88976377952756,"color":"rgba(0,186,56,1)","dash":"solid"},"frame":null},{"x":[1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007],"y":[4.77823086374099,4.78763755687842,4.81521236229935,4.84995350703073,4.88420042050358,4.93849971114474,4.99384608158126,5.044586793349,5.1000636731628,5.16318523665565,5.23139822162385,5.30011484224232],"text":["year: 1952<br />pop_val:      60011<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1957<br />pop_val:      61325<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1962<br />pop_val:      65345<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1967<br />pop_val:      70787<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1972<br />pop_val:      76595<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1977<br />pop_val:      86796<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1982<br />pop_val:      98593<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1987<br />pop_val:     110812<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1992<br />pop_val:     125911<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1997<br />pop_val:     145608<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 2002<br />pop_val:     170372<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 2007<br />pop_val:     199579<br />pop_attribute: min_pop<br />pop_attribute: min_pop"],"type":"scatter","mode":"markers+lines","marker":{"autocolorscale":false,"color":"rgba(97,156,255,1)","opacity":1,"size":5.66929133858268,"symbol":"circle","line":{"width":1.88976377952756,"color":"rgba(97,156,255,1)"}},"hoveron":"points","name":"min_pop","legendgroup":"min_pop","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","line":{"width":1.88976377952756,"color":"rgba(97,156,255,1)","dash":"solid"},"frame":null},{"x":[1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007],"y":[5.82141526061797,5.88360466092229,5.94816738303424,5.98234134784264,5.98909324727121,6.01661930947576,6.04785055878239,6.07603426556859,6.07323027369527,6.05618080493804,6.04211538123535,6.02391389457986],"text":["year: 1952<br />pop_val:     662850<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1957<br />pop_val:     764900<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1962<br />pop_val:     887498<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1967<br />pop_val:     960155<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1972<br />pop_val:     975199<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1977<br />pop_val:    1039009<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1982<br />pop_val:    1116479<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1987<br />pop_val:    1191336<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1992<br />pop_val:    1183669<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1997<br />pop_val:    1138101<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 2002<br />pop_val:    1101832<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 2007<br />pop_val:    1056608<br />pop_attribute: min_pop<br />pop_attribute: min_pop"],"type":"scatter","mode":"markers+lines","marker":{"autocolorscale":false,"color":"rgba(97,156,255,1)","opacity":1,"size":5.66929133858268,"symbol":"circle","line":{"width":1.88976377952756,"color":"rgba(97,156,255,1)"}},"hoveron":"points","name":"min_pop","legendgroup":"min_pop","showlegend":false,"xaxis":"x2","yaxis":"y","hoverinfo":"text","line":{"width":1.88976377952756,"color":"rgba(97,156,255,1)","dash":"solid"},"frame":null},{"x":[1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007],"y":[5.0807959874006,5.14193553517069,5.23518238846469,5.30574248830421,5.36323580448369,5.47335556698286,5.5774538835845,5.65764089523629,5.72385858260487,5.77710841641902,5.81716658748401,5.85038459962796],"text":["year: 1952<br />pop_val:     120447<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1957<br />pop_val:     138655<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1962<br />pop_val:     171863<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1967<br />pop_val:     202182<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1972<br />pop_val:     230800<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1977<br />pop_val:     297410<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1982<br />pop_val:     377967<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1987<br />pop_val:     454612<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1992<br />pop_val:     529491<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1997<br />pop_val:     598561<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 2002<br />pop_val:     656397<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 2007<br />pop_val:     708573<br />pop_attribute: min_pop<br />pop_attribute: min_pop"],"type":"scatter","mode":"markers+lines","marker":{"autocolorscale":false,"color":"rgba(97,156,255,1)","opacity":1,"size":5.66929133858268,"symbol":"circle","line":{"width":1.88976377952756,"color":"rgba(97,156,255,1)"}},"hoveron":"points","name":"min_pop","legendgroup":"min_pop","showlegend":false,"xaxis":"x3","yaxis":"y","hoverinfo":"text","line":{"width":1.88976377952756,"color":"rgba(97,156,255,1)","dash":"solid"},"frame":null},{"x":[1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007],"y":[5.17015019303463,5.2177733774015,5.26019783994511,5.29814540763779,5.32071735060084,5.34600657452377,5.36921028949648,5.38859137197238,5.41331988536718,5.4332768739594,5.45943772441173,5.47990770539729],"text":["year: 1952<br />pop_val:     147962<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1957<br />pop_val:     165110<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1962<br />pop_val:     182053<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1967<br />pop_val:     198676<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1972<br />pop_val:     209275<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1977<br />pop_val:     221823<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1982<br />pop_val:     233997<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1987<br />pop_val:     244676<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1992<br />pop_val:     259012<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1997<br />pop_val:     271192<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 2002<br />pop_val:     288030<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 2007<br />pop_val:     301931<br />pop_attribute: min_pop<br />pop_attribute: min_pop"],"type":"scatter","mode":"markers+lines","marker":{"autocolorscale":false,"color":"rgba(97,156,255,1)","opacity":1,"size":5.66929133858268,"symbol":"circle","line":{"width":1.88976377952756,"color":"rgba(97,156,255,1)"}},"hoveron":"points","name":"min_pop","legendgroup":"min_pop","showlegend":false,"xaxis":"x","yaxis":"y2","hoverinfo":"text","line":{"width":1.88976377952756,"color":"rgba(97,156,255,1)","dash":"solid"},"frame":null},{"x":[1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007],"y":[6.29989805326459,6.34818936041327,6.39594637102175,6.4358682451565,6.4667341988263,6.50035999235202,6.50659296475259,6.52076720533923,6.53626468947901,6.56539759493456,6.59195866682252,6.61445120277575],"text":["year: 1952<br />pop_val:    1994794<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1957<br />pop_val:    2229407<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1962<br />pop_val:    2488550<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1967<br />pop_val:    2728150<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1972<br />pop_val:    2929100<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1977<br />pop_val:    3164900<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1982<br />pop_val:    3210650<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1987<br />pop_val:    3317166<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1992<br />pop_val:    3437674<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 1997<br />pop_val:    3676187<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 2002<br />pop_val:    3908037<br />pop_attribute: min_pop<br />pop_attribute: min_pop","year: 2007<br />pop_val:    4115771<br />pop_attribute: min_pop<br />pop_attribute: min_pop"],"type":"scatter","mode":"markers+lines","marker":{"autocolorscale":false,"color":"rgba(97,156,255,1)","opacity":1,"size":5.66929133858268,"symbol":"circle","line":{"width":1.88976377952756,"color":"rgba(97,156,255,1)"}},"hoveron":"points","name":"min_pop","legendgroup":"min_pop","showlegend":false,"xaxis":"x2","yaxis":"y2","hoverinfo":"text","line":{"width":1.88976377952756,"color":"rgba(97,156,255,1)","dash":"solid"},"frame":null}],"layout":{"margin":{"t":55.4520547945205,"r":7.30593607305936,"b":40.1826484018265,"l":54.7945205479452},"plot_bgcolor":"rgba(255,255,255,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"title":"Population distribution of each continent over the years","titlefont":{"color":"rgba(0,0,0,1)","family":"","size":17.5342465753425},"xaxis":{"domain":[0,0.325179386823222],"automargin":true,"type":"linear","autorange":false,"range":[1949.25,2009.75],"tickmode":"array","ticktext":["1960","1980","2000"],"tickvals":[1960,1980,2000],"categoryorder":"array","categoryarray":["1960","1980","2000"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y2","title":"","titlefont":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"hoverformat":".2f"},"annotations":[{"text":"year","x":0.5,"y":-0.0353881278538813,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"top","annotationType":"axis"},{"text":"Population distribution","x":-0.0448467058056099,"y":0.5,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"xref":"paper","yref":"paper","textangle":-90,"xanchor":"right","yanchor":"center","annotationType":"axis"},{"text":"Africa","x":0.162589693411611,"y":1,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(26,26,26,1)","family":"","size":11.689497716895},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"bottom"},{"text":"Americas","x":0.5,"y":1,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(26,26,26,1)","family":"","size":11.689497716895},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"bottom"},{"text":"Asia","x":0.837410306588389,"y":1,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(26,26,26,1)","family":"","size":11.689497716895},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"bottom"},{"text":"Europe","x":0.162589693411611,"y":0.470319634703196,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(26,26,26,1)","family":"","size":11.689497716895},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"bottom"},{"text":"Oceania","x":0.5,"y":0.470319634703196,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(26,26,26,1)","family":"","size":11.689497716895},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"bottom"},{"text":"Population distribution","x":1.02,"y":1,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"left","yanchor":"bottom","legendTitle":true}],"yaxis":{"domain":[0.529680365296804,1],"automargin":true,"type":"linear","autorange":false,"range":[4.56113538497463,9.3372359178346],"tickmode":"array","ticktext":["1e+05","1e+06","1e+07","1e+08","1e+09"],"tickvals":[5,6,7,8,9],"categoryorder":"array","categoryarray":["1e+05","1e+06","1e+07","1e+08","1e+09"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x","title":"","titlefont":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":"transparent","line":{"color":"rgba(51,51,51,1)","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0,"x1":0.325179386823222,"y0":0.529680365296804,"y1":1},{"type":"rect","fillcolor":"rgba(190,190,190,1)","line":{"color":"rgba(51,51,51,1)","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0,"x1":0.325179386823222,"y0":0,"y1":23.37899543379,"yanchor":1,"ysizemode":"pixel"},{"type":"rect","fillcolor":"transparent","line":{"color":"rgba(51,51,51,1)","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0.341487279843444,"x1":0.658512720156556,"y0":0.529680365296804,"y1":1},{"type":"rect","fillcolor":"rgba(190,190,190,1)","line":{"color":"rgba(51,51,51,1)","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0.341487279843444,"x1":0.658512720156556,"y0":0,"y1":23.37899543379,"yanchor":1,"ysizemode":"pixel"},{"type":"rect","fillcolor":"transparent","line":{"color":"rgba(51,51,51,1)","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0.674820613176778,"x1":1,"y0":0.529680365296804,"y1":1},{"type":"rect","fillcolor":"rgba(190,190,190,1)","line":{"color":"rgba(51,51,51,1)","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0.674820613176778,"x1":1,"y0":0,"y1":23.37899543379,"yanchor":1,"ysizemode":"pixel"},{"type":"rect","fillcolor":"transparent","line":{"color":"rgba(51,51,51,1)","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0,"x1":0.325179386823222,"y0":0,"y1":0.470319634703196},{"type":"rect","fillcolor":"rgba(190,190,190,1)","line":{"color":"rgba(51,51,51,1)","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0,"x1":0.325179386823222,"y0":0,"y1":23.37899543379,"yanchor":0.470319634703196,"ysizemode":"pixel"},{"type":"rect","fillcolor":"transparent","line":{"color":"rgba(51,51,51,1)","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0.341487279843444,"x1":0.658512720156556,"y0":0,"y1":0.470319634703196},{"type":"rect","fillcolor":"rgba(190,190,190,1)","line":{"color":"rgba(51,51,51,1)","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0.341487279843444,"x1":0.658512720156556,"y0":0,"y1":23.37899543379,"yanchor":0.470319634703196,"ysizemode":"pixel"}],"xaxis2":{"type":"linear","autorange":false,"range":[1949.25,2009.75],"tickmode":"array","ticktext":["1960","1980","2000"],"tickvals":[1960,1980,2000],"categoryorder":"array","categoryarray":["1960","1980","2000"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"domain":[0.341487279843444,0.658512720156556],"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y2","title":"","titlefont":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"hoverformat":".2f"},"xaxis3":{"type":"linear","autorange":false,"range":[1949.25,2009.75],"tickmode":"array","ticktext":["1960","1980","2000"],"tickvals":[1960,1980,2000],"categoryorder":"array","categoryarray":["1960","1980","2000"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"domain":[0.674820613176778,1],"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y2","title":"","titlefont":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"hoverformat":".2f"},"yaxis2":{"type":"linear","autorange":false,"range":[4.56113538497463,9.3372359178346],"tickmode":"array","ticktext":["1e+05","1e+06","1e+07","1e+08","1e+09"],"tickvals":[5,6,7,8,9],"categoryorder":"array","categoryarray":["1e+05","1e+06","1e+07","1e+08","1e+09"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"domain":[0,0.470319634703196],"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x","title":"","titlefont":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"hoverformat":".2f"},"showlegend":true,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.88976377952756,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.689497716895},"y":0.93503937007874},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":[{"name":"Collaborate","icon":{"width":1000,"ascent":500,"descent":-50,"path":"M487 375c7-10 9-23 5-36l-79-259c-3-12-11-23-22-31-11-8-22-12-35-12l-263 0c-15 0-29 5-43 15-13 10-23 23-28 37-5 13-5 25-1 37 0 0 0 3 1 7 1 5 1 8 1 11 0 2 0 4-1 6 0 3-1 5-1 6 1 2 2 4 3 6 1 2 2 4 4 6 2 3 4 5 5 7 5 7 9 16 13 26 4 10 7 19 9 26 0 2 0 5 0 9-1 4-1 6 0 8 0 2 2 5 4 8 3 3 5 5 5 7 4 6 8 15 12 26 4 11 7 19 7 26 1 1 0 4 0 9-1 4-1 7 0 8 1 2 3 5 6 8 4 4 6 6 6 7 4 5 8 13 13 24 4 11 7 20 7 28 1 1 0 4 0 7-1 3-1 6-1 7 0 2 1 4 3 6 1 1 3 4 5 6 2 3 3 5 5 6 1 2 3 5 4 9 2 3 3 7 5 10 1 3 2 6 4 10 2 4 4 7 6 9 2 3 4 5 7 7 3 2 7 3 11 3 3 0 8 0 13-1l0-1c7 2 12 2 14 2l218 0c14 0 25-5 32-16 8-10 10-23 6-37l-79-259c-7-22-13-37-20-43-7-7-19-10-37-10l-248 0c-5 0-9-2-11-5-2-3-2-7 0-12 4-13 18-20 41-20l264 0c5 0 10 2 16 5 5 3 8 6 10 11l85 282c2 5 2 10 2 17 7-3 13-7 17-13z m-304 0c-1-3-1-5 0-7 1-1 3-2 6-2l174 0c2 0 4 1 7 2 2 2 4 4 5 7l6 18c0 3 0 5-1 7-1 1-3 2-6 2l-173 0c-3 0-5-1-8-2-2-2-4-4-4-7z m-24-73c-1-3-1-5 0-7 2-2 3-2 6-2l174 0c2 0 5 0 7 2 3 2 4 4 5 7l6 18c1 2 0 5-1 6-1 2-3 3-5 3l-174 0c-3 0-5-1-7-3-3-1-4-4-5-6z"},"click":"function(gd) { \n        // is this being viewed in RStudio?\n        if (location.search == '?viewer_pane=1') {\n          alert('To learn about plotly for collaboration, visit:\\n https://cpsievert.github.io/plotly_book/plot-ly-for-collaboration.html');\n        } else {\n          window.open('https://cpsievert.github.io/plotly_book/plot-ly-for-collaboration.html', '_blank');\n        }\n      }"}],"cloud":false},"source":"A","attrs":{"6afc5aed415e":{"x":{},"y":{},"colour":{},"type":"scatter"},"6afc12781f19":{"x":{},"y":{},"colour":{}}},"cur_data":"6afc5aed415e","visdat":{"6afc5aed415e":["function (y) ","x"],"6afc12781f19":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"base_url":"https://plot.ly"},"evals":["config.modeBarButtonsToAdd.0.click"],"jsHooks":[]}</script><!--/html_preserve-->

In addition, we can make 3D plot using `plotly`.


```r
gapminder %>% 
  # group by year and continent
  group_by(year, continent) %>%
  # calcuate summaries of pop
  summarize(
    max_pop = max(pop)
  ) %>% 
  group_by(continent) %>% 
  plot_ly(
    x = ~year,
    y = ~continent,
    z = ~max_pop,
    type = "scatter3d",
    mode = "markers + lines",
    color = ~continent
  ) %>% 
  layout(
    scene = list(
      xaxis = list(title = "Year"),
      yaxis = list(title = "Continent"),
      zaxis = list(title = "Maximum Population")
    )
  )
```

<!--html_preserve--><div id="htmlwidget-eb3df55e93164070eb14" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-eb3df55e93164070eb14">{"x":{"visdat":{"6afc13e84921":["function () ","plotlyVisDat"]},"cur_data":"6afc13e84921","attrs":{"6afc13e84921":{"x":{},"y":{},"z":{},"mode":"markers + lines","color":{},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter3d"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"scene":{"xaxis":{"title":"Year"},"yaxis":{"title":"Continent"},"zaxis":{"title":"Maximum Population"}},"yaxis":{"type":"category","categoryorder":"array","categoryarray":["Africa","Americas","Asia","Europe","Oceania"]},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":[{"name":"Collaborate","icon":{"width":1000,"ascent":500,"descent":-50,"path":"M487 375c7-10 9-23 5-36l-79-259c-3-12-11-23-22-31-11-8-22-12-35-12l-263 0c-15 0-29 5-43 15-13 10-23 23-28 37-5 13-5 25-1 37 0 0 0 3 1 7 1 5 1 8 1 11 0 2 0 4-1 6 0 3-1 5-1 6 1 2 2 4 3 6 1 2 2 4 4 6 2 3 4 5 5 7 5 7 9 16 13 26 4 10 7 19 9 26 0 2 0 5 0 9-1 4-1 6 0 8 0 2 2 5 4 8 3 3 5 5 5 7 4 6 8 15 12 26 4 11 7 19 7 26 1 1 0 4 0 9-1 4-1 7 0 8 1 2 3 5 6 8 4 4 6 6 6 7 4 5 8 13 13 24 4 11 7 20 7 28 1 1 0 4 0 7-1 3-1 6-1 7 0 2 1 4 3 6 1 1 3 4 5 6 2 3 3 5 5 6 1 2 3 5 4 9 2 3 3 7 5 10 1 3 2 6 4 10 2 4 4 7 6 9 2 3 4 5 7 7 3 2 7 3 11 3 3 0 8 0 13-1l0-1c7 2 12 2 14 2l218 0c14 0 25-5 32-16 8-10 10-23 6-37l-79-259c-7-22-13-37-20-43-7-7-19-10-37-10l-248 0c-5 0-9-2-11-5-2-3-2-7 0-12 4-13 18-20 41-20l264 0c5 0 10 2 16 5 5 3 8 6 10 11l85 282c2 5 2 10 2 17 7-3 13-7 17-13z m-304 0c-1-3-1-5 0-7 1-1 3-2 6-2l174 0c2 0 4 1 7 2 2 2 4 4 5 7l6 18c0 3 0 5-1 7-1 1-3 2-6 2l-173 0c-3 0-5-1-8-2-2-2-4-4-4-7z m-24-73c-1-3-1-5 0-7 2-2 3-2 6-2l174 0c2 0 5 0 7 2 3 2 4 4 5 7l6 18c1 2 0 5-1 6-1 2-3 3-5 3l-174 0c-3 0-5-1-7-3-3-1-4-4-5-6z"},"click":"function(gd) { \n        // is this being viewed in RStudio?\n        if (location.search == '?viewer_pane=1') {\n          alert('To learn about plotly for collaboration, visit:\\n https://cpsievert.github.io/plotly_book/plot-ly-for-collaboration.html');\n        } else {\n          window.open('https://cpsievert.github.io/plotly_book/plot-ly-for-collaboration.html', '_blank');\n        }\n      }"}],"cloud":false},"data":[{"x":[1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007],"y":["Africa","Africa","Africa","Africa","Africa","Africa","Africa","Africa","Africa","Africa","Africa","Africa"],"z":[33119096,37173340,41871351,47287752,53740085,62209173,73039376,81551520,93364244,106207839,119901274,135031164],"mode":"markers + lines","type":"scatter3d","name":"Africa","marker":{"color":"rgba(102,194,165,1)","line":{"color":"rgba(102,194,165,1)"}},"textfont":{"color":"rgba(102,194,165,1)"},"error_y":{"color":"rgba(102,194,165,1)"},"error_x":{"color":"rgba(102,194,165,1)"},"line":{"color":"rgba(102,194,165,1)"},"frame":null},{"x":[1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007],"y":["Americas","Americas","Americas","Americas","Americas","Americas","Americas","Americas","Americas","Americas","Americas","Americas"],"z":[157553000,171984000,186538000,198712000,209896000,220239000,232187835,242803533,256894189,272911760,287675526,301139947],"mode":"markers + lines","type":"scatter3d","name":"Americas","marker":{"color":"rgba(252,141,98,1)","line":{"color":"rgba(252,141,98,1)"}},"textfont":{"color":"rgba(252,141,98,1)"},"error_y":{"color":"rgba(252,141,98,1)"},"error_x":{"color":"rgba(252,141,98,1)"},"line":{"color":"rgba(252,141,98,1)"},"frame":null},{"x":[1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007],"y":["Asia","Asia","Asia","Asia","Asia","Asia","Asia","Asia","Asia","Asia","Asia","Asia"],"z":[556263527,637408000,665770000,754550000,862030000,943455000,1000281000,1084035000,1164970000,1230075000,1280400000,1318683096],"mode":"markers + lines","type":"scatter3d","name":"Asia","marker":{"color":"rgba(141,160,203,1)","line":{"color":"rgba(141,160,203,1)"}},"textfont":{"color":"rgba(141,160,203,1)"},"error_y":{"color":"rgba(141,160,203,1)"},"error_x":{"color":"rgba(141,160,203,1)"},"line":{"color":"rgba(141,160,203,1)"},"frame":null},{"x":[1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007],"y":["Europe","Europe","Europe","Europe","Europe","Europe","Europe","Europe","Europe","Europe","Europe","Europe"],"z":[69145952,71019069,73739117,76368453,78717088,78160773,78335266,77718298,80597764,82011073,82350671,82400996],"mode":"markers + lines","type":"scatter3d","name":"Europe","marker":{"color":"rgba(231,138,195,1)","line":{"color":"rgba(231,138,195,1)"}},"textfont":{"color":"rgba(231,138,195,1)"},"error_y":{"color":"rgba(231,138,195,1)"},"error_x":{"color":"rgba(231,138,195,1)"},"line":{"color":"rgba(231,138,195,1)"},"frame":null},{"x":[1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007],"y":["Oceania","Oceania","Oceania","Oceania","Oceania","Oceania","Oceania","Oceania","Oceania","Oceania","Oceania","Oceania"],"z":[8691212,9712569,10794968,11872264,13177000,14074100,15184200,16257249,17481977,18565243,19546792,20434176],"mode":"markers + lines","type":"scatter3d","name":"Oceania","marker":{"color":"rgba(166,216,84,1)","line":{"color":"rgba(166,216,84,1)"}},"textfont":{"color":"rgba(166,216,84,1)"},"error_y":{"color":"rgba(166,216,84,1)"},"error_x":{"color":"rgba(166,216,84,1)"},"line":{"color":"rgba(166,216,84,1)"},"frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"base_url":"https://plot.ly"},"evals":["config.modeBarButtonsToAdd.0.click"],"jsHooks":[]}</script><!--/html_preserve-->

# Part 4: Writing figures to file

## Arguments of `ggsave()`

Let's play around arguments of `ggsave()`. For example, width, height, resolution, and text scale.

### Differenct widths and heights


```r
# default width and height
ggsave("./ggsave/1.png")
```

```
## Saving 7 x 5 in image
```

![1.png](./ggsave/1.png)


```r
# arbitrary width and height
ggsave("./ggsave/2.png", width = 10, height = 5)
```

![2.png](./ggsave/2.png)

### Different resolutions

Here we try to generate image of two resolutions, one as normal and one very low.


```r
# normal resolution
ggsave("./ggsave/3.png", dpi = 300)
```

```
## Saving 7 x 5 in image
```

![3.png](./ggsave/3.png)


```r
# low resolution
ggsave("./ggsave/4.png", dpi = 10)
```

```
## Saving 7 x 5 in image
```
![4.png](./ggsave/4.png)

## Various graphics devices


```r
# vector format
ggsave("./ggsave/5.eps", device = "eps")
```

```
## Saving 7 x 5 in image
```

*(An ESP file cannot be loaded into an HTML file, so it is ignored.)*


```r
# raster format
ggsave("./ggsave/6.bmp", device = "bmp")
```

```
## Saving 7 x 5 in image
```

![6.bmp](./ggsave/6.bmp)

The diffience is, vector format images store polygons, so when it is scaled, the polygons are scaled as well, so they always look the same. While for raster format images, pixels are stored, so image becomes blurry when scaled up.

## Explicit provision of the plot object `p`

Without explicit provision of the plot object `p`, `ggsave()` always tries to save the lastest figure (in our case, it is `p_new`). Therefore, we need to provide the plot object if we want to save other figures, for example, `p_ori`.


```r
# save p_ori
ggsave("./ggsave/7.png", plot = p_ori)
```

```
## Saving 7 x 5 in image
```

![7.png](./ggsave/7.png)

# But I want to do more!

**Make a deeper exploration of the forcats packages.**

According to [this reference](http://r4ds.had.co.nz/factors.html), we try to explore the following functions of forcats packages:

- `fct_relevel()`;
- `fct_reorder2()`;
- `fct_infreq()` and `fct_rev()`;
- `fct_recode()`;
- `fct_collapse()`; and
- `fct_lump()`.

## `fct_relevel()`

We can use `fct_relevel()` to manually reorder levels. For example, we can move Canada to be the first data in this example (which in the figure is the bottom one).


```r
drop_levels %>% 
  # try to only show a continent
  filter(continent == "Americas") %>% 
  # group by country
  group_by(country) %>% 
  # calcuate maximum population for each country
  summarize(
    max_pop = max(pop)
  ) %>% 
  # arrange by max_pop
  arrange(max_pop) %>%
  # show preview of resultant levels
  ggplot(aes(x = max_pop, y = fct_relevel(country, "Canada"), color = country)) +
  # make it a scatterplot
  geom_point() + 
  # scale x axis by log10
  scale_x_log10() +
  # change axis labels
  xlab("Maximum population") +
  ylab("country") +
  # add title
  labs(title = "Maximum population of countries in Americas") +
  # highlight Canada
  scale_y_discrete(labels = c("Canada" = expression(bold(Canada)), parse = TRUE)) +
  # add theme
  theme_bw() +
  theme(
    strip.background = element_rect(fill = "grey"),
    panel.background = element_rect(fill = "white")
  )
```

![](hw05_files/figure-html/unnamed-chunk-29-1.png)<!-- -->

## `fct_reorder2()`

We can use `fct_reorder2()` to reorder by two variables. For example, in the following example, we reorder by population first then GDP per capita (though it is not obvious).


```r
gapminder %>% 
  # show only Oceania
  filter(continent == "Oceania") %>% 
  # pop as x axis and gdpPercap as y axis
  ggplot(aes(x = pop, y = gdpPercap, color = fct_reorder2(country, pop, gdpPercap, min))) +
  # make it a line plot
  geom_line() + 
  # change label
  labs(color = "Country") +
  # add title
  labs(
    x = "Population",
    y = "GDP per capita",
    title = "GDP per capita vs population"
  ) +
  # scale x by log10
  scale_x_log10() +
  # add theme
  theme_bw()
```

![](hw05_files/figure-html/unnamed-chunk-30-1.png)<!-- -->

## `fct_infreq()` and `fct_rev()`

We use `fct_infreq()` to order levels in increasing frequency and `fct_rev()` to reverse order. They are usually used in bar plots.


```r
gapminder %>% 
  # show only a continent
  filter(continent == "Americas") %>% 
  # filter countreis with gdpPercap larger than 15,000
  filter(gdpPercap >= 15000) %>% 
  # reorder levels of country
  mutate(
    country = country %>% fct_infreq() %>% fct_rev()
  ) %>% 
  # country as x axis
  ggplot(aes(x = country, fill = country)) +
  # make it as a bar plot
  geom_bar() +
  # add title
  labs(
    x = "Country",
    y = "Count",
    title = "Number of years with GDP per capita >= 15,000"
  ) +
  # add theme
  theme_bw()
```

![](hw05_files/figure-html/unnamed-chunk-31-1.png)<!-- -->


## `fct_recode()`

`fct_recode()` can be used to manully change the names of levels. For example, we try to change the name of "United States" in the above example.


```r
gapminder %>% 
  # show only a continent
  filter(continent == "Americas") %>% 
  # filter countreis with gdpPercap larger than 15,000
  filter(gdpPercap >= 15000) %>% 
  # reorder levels of country, and change name of "United States"
  mutate(
    country = country %>% fct_infreq() %>% fct_rev() %>% 
      fct_recode(
        "USA" = "United States"
      )
  ) %>% 
  # country as x axis
  ggplot(aes(x = country, fill = country)) +
  # make it as a bar plot
  geom_bar() +
  # add title
  labs(
    x = "Country",
    y = "Count",
    title = "Number of years with GDP per capita >= 15,000"
  ) +
  # add theme
  theme_bw()
```

![](hw05_files/figure-html/unnamed-chunk-32-1.png)<!-- -->

## `fct_collapse()`

We can try to use `fct_collapse()` to manually combine levels into groups. For example, we combined "Canada" and "USA" together in the above example.


```r
gapminder %>% 
  # show only a continent
  filter(continent == "Americas") %>% 
  # filter countreis with gdpPercap larger than 15,000
  filter(gdpPercap >= 15000) %>% 
  # reorder levels of country, and change name of "United States", and combine "Canada" and "USA"
  mutate(
    country = country %>% fct_infreq() %>% fct_rev() %>% 
      fct_recode(
        "USA" = "United States"
      ) %>% 
      fct_collapse(
        "North Americas" = c("Canada", "USA")
      )
  ) %>% 
  # country as x axis
  ggplot(aes(x = country, fill = country)) +
  # make it as a bar plot
  geom_bar() +
  # add title
  labs(
    x = "Country",
    y = "Count",
    title = "Number of years with GDP per capita >= 15,000"
  ) +
  # add theme
  theme_bw()
```

![](hw05_files/figure-html/unnamed-chunk-33-1.png)<!-- -->

## `fct_lump()`

`fct_lump()` try to automaticaly aggregate groups.


```r
gapminder %>% 
  # show only a continent
  filter(continent == "Americas") %>% 
  # filter countreis with gdpPercap larger than 15,000
  filter(gdpPercap >= 15000) %>% 
  # reorder levels of country, and let forcats lump groups for us
  mutate(
    country = country %>% fct_infreq() %>% fct_rev() %>% fct_lump()
  ) %>% 
  # country as x axis
  ggplot(aes(x = country, fill = country)) +
  # make it as a bar plot
  geom_bar() +
  # add title
  labs(
    x = "Country",
    y = "Count",
    title = "Number of years with GDP per capita >= 15,000"
  ) +
  # add theme
  theme_bw()
```

![](hw05_files/figure-html/unnamed-chunk-34-1.png)<!-- -->

# Refereces
- [R for Data Science - Factors](http://r4ds.had.co.nz/factors.html)
